### PR TITLE
Replace Version Command with Cobra

### PR DESCRIPTION
**Pull request by rustydb**
# Summary and Scope

Minify the code for printing the version by leveraging Cobra's built-in `version` parameter.

This is a small contribution, it served more as an exercise for myself to get the repo cloned and to start playing with it.

## Testing

When `cani` is built on a tag:
```bash
[545]rusty@C02F43JEMD6P:~/gitstuffs/cray-shasta/cani> ./bin/cani --version
cani version 1.2.1
```

When `cani` is built on a commit after a tag.
```bash
[548]rusty@C02F43JEMD6P:~/gitstuffs/cray-shasta/cani> ./bin/cani --version
cani version 0.2.0~22~g5ed008b
```

When `cani` is built with uncommitted changes in the repository folder.
```bash
[538]rusty@C02F43JEMD6P:~/gitstuffs/cray-shasta/cani> ./bin/cani --version
cani version 0.2.0~22~gb56005a-dirty-2023-09-21T18:04:17Z
```

# Risks and Mitigations

### CODE REVIEW

**Comment by jacobsalmela** [comment]
Slick.  Just need to update those fixtures with the new output

**Comment by jacobsalmela** [comment]
Oh looks like you accidentally removed some files, too like our fancy logo.

**Comment by rustydb** [comment]
I ran `make lint`, but it identified more than my file so I left it alone.

> Oh looks like you accidentally removed some files, too like our fancy logo.

Ok, that explains the commit I saw. I had this branch for some time, and had a commit that compressed the logo. I incidentally had a similar commit in another repo, and thought I had messed something up. I'll resolve that.

**Comment by rustydb** [comment]
> Oh looks like you accidentally removed some files, too like our fancy logo.

It's not removed, it's shrunk. I shrunk it from 44kb to 16kb.

**Comment by jacobsalmela** [comment]
I see now.  I don't think we need that as part of this PR though?

**Comment by rustydb** [comment]
> I see now. I don't think we need that as part of this PR though?

Sure, I had it as a separate commit and it got squashed in my rebase. Totally forgot about it when I made the PR.

**Comment by jacobsalmela** [comment]
I see, you can remove that version fixture since it is not a command any more.  Then just update the shellspec test

**Review by jacobsalmela — APPROVED** [review]

**Review by shunr-hpe — APPROVED** [review]

**Pull request merged**
